### ISSUE TITLE
[Feature] support read-only root fs

### ISSUE THREAD

**Issue by ngrigoriev** [mariadb-operator/mariadb-operator#100]
**Is your feature request related to a problem? Please describe.**

I would like to have mariadb running with root fs readonly, like all containers should.

**Describe the solution you'd like**

Either more direct support for it or at least an ability to define additional custom volumes for the pod (e.g /tmp, /var/lib)

**Describe alternatives you've considered**

There does not seem to be any options today to achieve it. The read-only root fs mode can be set via securitycontext, but there seems to be no way to provide the addional (emptyDir) volumes to mariadb pod.

**Comment by mmontes11** [comment]
Hey @ngrigoriev ! Thanks for raising this 

This has been addressed in this PR:
- https://github.com/mariadb-operator/mariadb-operator/pull/101

Now you are able to specify extra `spec.volumes` and `spec.volumeMounts`, see this example:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/config/samples/mariadb_v1alpha1_mariadb.yaml#L32..L37

I think it should cover your case, let me know otherwise. Thanks 🙏🏻
