### ISSUE TITLE
Semi-Sync Replication breaks if initial binlogs have been purged

### ISSUE THREAD

**Issue by svenpecher** [mariadb-operator/mariadb-operator#231]
**Describe the bug**

In the context of a semi-sync replication setup it seems that during ConfigureReplica (e.g. when a replica pod was restarted) in any case the slave position is resetted to an empty value:

```
func (c *Client) ResetSlavePos(ctx context.Context) error {
	sql := fmt.Sprintf("SET @@global.%s='';", "gtid_slave_pos")
	return c.Exec(ctx, sql)
} 
```

That seems to cause issues if initial binlog files have been purged in the primary :

```
[ERROR] Master 'mariadb-operator': Error reading packet from server: Could not find GTID state requested by slave in any binlog files. Probably the slave state is too old and required binlog files have been purged. (server_errno=1236)
[ERROR] Master 'mariadb-operator': Slave I/O: Got fatal error 1236 from master when reading data from binary log: 'Could not find GTID state requested by slave in any binlog files. Probably the slave state is too old and required binlog files have been purged.', Internal MariaDB error code: 1236`
```

Related to:
- https://github.com/mariadb-operator/mariadb-operator/issues/141

**Is the bug related to Galera?**
no

**Expected behaviour**
Replication should not break if initial binlogs have been purged and if GTID of replica is still within remaining binlogs. Hence from my point of view the gtid_slave_pos should only be set empty in case of a fresh DB. In other cases should be left untouched (...I might be wrong with this).

**Steps to reproduce the bug**
Purge some binlogs in Primary, delete Replica pod, wait for Pod to come up and wait for Replication to fail after reconcile.

**Environment details**:
- mariadb-operator version: 19

**Comment by svenpecher** [comment]
Actually my issue here seems to pretty much the same as the unsolved but closed issue #141

**Comment by svenpecher** [comment]
As I understand the ResetSlavePos happens during ConfigureReplica which seems to be executed during the following procedures:

1. reconcilePodReady
2. reconcileReplicas
3. connectReplicasToNewPrimary
4. changeCurrentPrimaryToReplica

For 3. and 4. it seems right to reset gtid_slave_pos.

For 1. and 2. this is a bit unexpected: I would assume that here each replica has a certain replication state (gtid_slave_pos), which gets lost here. From my understanding here it rather makes sense to keep the current position without overwriting it.

@mmontes11 what do you think about that?

**Comment by mmontes11** [comment]
Hey there @svenpecher ! Thanks for bringing this up and your detailed analysis.

This is indeed related to the following issue:
- https://github.com/mariadb-operator/mariadb-operator/issues/141

We will be implementing some replication enhancements in this release, which include choosing the furthest advanced replica in the primary switchover, see:
- https://github.com/mariadb-operator/mariadb-operator/issues/193
- https://github.com/mariadb-operator/mariadb-operator/issues/209

Ideally, I would like to avoid resetting `gtid_slave_pos` where possible to minimize this kind of situations like the one you report. Your suggestion makes sense, it's like a middleground, so I will have it in mind by the time I'm implementing this.

To give you some context, this reset with timeout was introduced because we've faced situations where the replication was stucked waiting for replicas be synced. In this step specifically:
https://github.com/mariadb-operator/mariadb-operator/blob/6ba1c800924c34e5ac56dcc11cec6ec81f23371d/pkg/controller/replication/switchover.go#L54

Switching to the furthest advanced replica might help with this? Maybe we don't need to wait for the furthest advanced replica to be sync with primary? 

Anyway avoid the reset it in the steps 1. and 2. does sound sensible.
