### ISSUE TITLE
[Feature] standardize image to make it look like Pod image

### ISSUE THREAD

**Issue by ms999** [mariadb-operator/mariadb-operator#261]
**Is your feature request related to a problem? Please describe.**

Standarize image to make it look like Pod image in mariadb-operator chart

**Describe the solution you'd like**

In mariadb-operator chart image entity has to be changed to look like in mariadb resource in v0.21.0. It has to be changed for controller and for webhook containers:

Replace these lines:
- image:
-   repository: mariadb-operator
-   tag: "v0.0.22"
-   pullPolicy: IfNotPresent

 with these lines:
+ image: mariadb-operator:v0.0.22
+ imagePullPolicy: IfNotPresent

**Describe alternatives you've considered**

**Additional context**

This change will allow to reference images using digest instead of tags in order to be more precise in image referencing.  

**Environment details**:
- Kubernetes version: any
- mariadb-operator version:  v0.0.22
- Install method: helm, OLM or static manifests - any
- Install flavour: minimal, recommended or custom. - any

**Comment by mmontes11** [comment]
Hey there @ms999! Thanks for reporting this

Although I do se your point in favour of standarization, I think there is a different de-facto standard followed in the helm charts to provide the image, see:
- https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L79
- https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L607
- https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml#L22

So we will be sticking to this format in the helm chart, since it is what a user would expect.

> This change will allow to reference images using digest instead of tags in order to be more precise in image referencing.

We can introduce a new `digest` field in the helm chart images and create a reusable helper function to build the image URL, see an example:

https://github.com/cert-manager/cert-manager/blob/d2f6bbe579fd9d5f88b82f9a4bfe9241709e9eb8/deploy/charts/cert-manager/templates/_helpers.tpl#L186

PRs welcome!
