### ISSUE TITLE
[Feature] Compress backup files

### ISSUE THREAD

**Issue by TheNozomi** [mariadb-operator/mariadb-operator#341]
**Is your feature request related to a problem? Please describe.**
When using mariadb-dump/mysqldump, you can pipe its output to a compression program, for instance, gzip or 7z, and compress the resulting dump file on a single step.
As far as I know, this is currently not possible with the mariadb-operator `Backup` resource, and if you want to compress the dump you have to do so manually.

**Describe the solution you'd like**
Add a `spec.compress` field to the `Backup` resource, which can be a boolean, or a string that indicates the compression type (gzip, 7z, zstd, etc.). If compression is enabled, the backup job would compress the file using the selected compression program, and then save it.

**Describe alternatives you've considered**
N/A

**Environment details**:
- Kubernetes version: 1.27.5
- Kubernetes distribution: k3s
- mariadb-operator version: 0.24.0
- Install method: Helm
- Install flavor: Recommended

**Additional context**
As for now, what we're doing to save compressed dumps is using the Backup resource to generate a dump, save it to an NFS volume mapped in Kubernetes, and then we have a cron job on the server that reads the file, compresses it using gzip, and uploads it to S3 using the AWS CLI.
Now that there's support for directly uploading dumps to S3 in mariadb-operator (which I've been testing and works well for our use case), it would be very useful to have the option of compressing the dumps before uploading them to S3, so we can eliminate the manual steps.

**Comment by mmontes11** [comment]
Hola @TheNozomi ! 100% this makes total sense to me.

Not only we should support it in the `Backups`, but also we should make the `Restore` resource compatible with it. As you said we should introduce a new field in the `Backup` resource indicating the compression algorithm:

```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
   compression: gzip
   ....
```
We don't need to change anything in the `Restore` API, as we already have a reference to the `Backup`:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Restore
metadata:
  name: restore
spec:
  backupRef:
    name: backup
  ...
```

Regarding the implementation, I would support this in our new [backup](https://github.com/mariadb-operator/mariadb-operator/blob/main/cmd/backup/main.go) and [restore](https://github.com/mariadb-operator/mariadb-operator/blob/main/cmd/backup/restore.go) subcommands:
- The `backup` subcommand  is responsible for process the backup files AFTER the `mariadb-backup` command is executed. This responsability includes pushing the files to S3, and now we could potentially COMPRESS the backups before doing so. Here:
https://github.com/mariadb-operator/mariadb-operator/blob/d679c20bc64cf099353fbcd063edf51960c9b35a/cmd/backup/main.go#L88

- The `restore` subcommand is responsible for processing the backup files BEFORE THE `mariadb` command is executed to restore them. This responsability includes pulling them from S3, and now we could potentially DECOMPRESS the backup before doing so. Here:
https://github.com/mariadb-operator/mariadb-operator/blob/d679c20bc64cf099353fbcd063edf51960c9b35a/cmd/backup/restore.go#L59

There are multiple reasons to do it in Go in these subcommands:
- Our images can stay minimal without depending on compression libraries
- Easier to test and maintain
- In general, Go based solutions tend to be more reliable and robust than bash scripts

In order to achieve this, and to support multiple compression strategies, we would need to be able to swap compression algoritms that implement [io.Reader](https://pkg.go.dev/io#Reader) (decompress) and [io.Writer](https://pkg.go.dev/io#Writer) (compress). We could leverage the compress package for this purpose:
- https://pkg.go.dev/compress

Initially I would support `gzip` and `zlib`, which seem to be the more popular among the supported in the `compress` package but I am open to suggestions here. And of course, the `spec.compression` field should be optional, which would mean that the `Backup`/ `Restore` resources work as they do currently.

Thoughts? Let me know what you think.

Contributions are welcome!

**Comment by eloo** [comment]
Hi there,

i have just discovered this operator while looking for a better solution of spinning up databases and backups separately and was pretty impressed by the feature set of this operator.

But compression is really a must have in my use case so its awesome that this topic is already being worked on. 
As i have seen the discussion about the compression algorithm maybe the following project could be a good reference:
https://github.com/tiredofit/docker-db-backup

I use this docker backup solution since a few years and its working pretty stable. 
Maybe it could give some inspiration about common backup options..

Further it would be great if backup encryption could be implemented together with compression.
Thats always a good option when you store your backup offsite ;) 

Thanks for this great operator!

**Comment by TheNozomi** [comment]
Hola @mmontes11! Thank you for the response. Yes, it's exactly what I've been thinking, and I agree that a go based solution would be a better approach than just invoking a binary. I just wasn't aware of the `compress` package (to be honest I'm pretty much new to the go ecosystem, that's the reason I didn't try to implement the feature myself). And, yes, I think having `gzip` and `zlib` support would be enough for the majority of use cases.

Also, thanks @eloo for mentioning `docker-db-backup`! Seems like I could look into using that in the meantime this feature gets implemented.

**Comment by majordhote** [comment]
That would be a great feature to reduce backup storage needs !

**Comment by RegisHubelia** [comment]
Hi, Thank you for the good work.  Not sure if this is the right channel or if I should add a new feature request - as compression would fix my immediate issue where the backup file is bigger than the allowed 5gb in a single put operation.  So the backup fails.  I have the option to separate the database backup operations, but uploading to s3 in part is also quite important so we don't hit this issue of upload limit in a single put operation...  Backup Encryption should also be on the pipeline to make it more production-ready as stated above.

**Comment by mmontes11** [comment]
Hey there @RegisHubelia ! We really appreciate this feedback, thank you

Compression first, and then encryption is definetly in our radar. After having prioritized [PITR](https://github.com/mariadb-operator/mariadb-operator/issues/507) in our roadmap, which makes use of S3, having S3 compression makes even more sense.

**Comment by phanimullapudi** [comment]
qpress is also commonly used compression algorithm

**Comment by mmontes11** [comment]
This was kindly contributed by @vixns ! We've decided to initially support the `gzip` (faster) and `bzip2` (better compression ratio) algorithms. Stay tuned for the next release!

**Comment by mohag** [comment]
zstd would be nice - it tend to outperform gzip and bzip2 by a LOT... (It would probably require exposing a level setting as well though...)

(The default settings takes 1/6th as long as gzip and compress somewhere between gzip and bzip2. Its best setting is a bit slower than bzip2 and compresses better (similar to xz's highest setting, in 1/5th the time)) ([Some benchmarks here](https://linuxreviews.org/Comparison_of_Compression_Algorithms))
