### ISSUE TITLE
[Bug]  No `podSecurityContext` on metrics deployments

### ISSUE THREAD

**Issue by gg-kialo** [mariadb-operator/mariadb-operator#348]
**Documentation**

- [x] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**

In 0.0.24 the metrics exporter was moved from a sidecar to a stand-alone deployment.
The stand-alone deployment doesn't have a `podSecurityContext` set, this means it can't be deployed in namespaces with enforced restrictive pod-security labels.

**Expected behaviour**

The metrics exporter should use the `podSecurityContext` set on the spec of the `MariaDB` object.
(Or a separate `podSecurityContext` can be set for the metrics exporter)

**Steps to reproduce the bug**

Create a MariaDB resource with:

```
metrics: 
  enabled: true
```

in a namespace with a restrictive PSS set with the labels:

```
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
```

**Debug information**

No `podSecurityContext` is being configured on the deployed here: https://github.com/mariadb-operator/mariadb-operator/blob/v0.0.24/pkg/builder/deployment_buider.go#L41-68

**Environment details**:
- Kubernetes version: 1.26
- Kubernetes distribution: EKS
- mariadb-operator version: 0.0.24
- Install method: static manifests
- Install flavor: custom

**Additional context**

**Comment by mmontes11** [comment]
Hey there @gg-kialo !

We only support `securityContext` at the `Pod`  level, since we are (only!) embedding  `ContainerTemplate` in `Exporter`:
https://github.com/mariadb-operator/mariadb-operator/blob/16b704268623b44cb9d1587d69fc7afd097edc30/api/v1alpha1/mariadb_types.go#L30
https://github.com/mariadb-operator/mariadb-operator/blob/16b704268623b44cb9d1587d69fc7afd097edc30/api/v1alpha1/base_types.go#L77

To align with the `MariaDB` type, we should also embed `PodTemplate`:
https://github.com/mariadb-operator/mariadb-operator/blob/16b704268623b44cb9d1587d69fc7afd097edc30/api/v1alpha1/base_types.go#L134
https://github.com/mariadb-operator/mariadb-operator/blob/16b704268623b44cb9d1587d69fc7afd097edc30/api/v1alpha1/mariadb_types.go#L157

and then make the changes in the `Deployment` builder you pointed out, it should be pretty similar to the `StatefulSet` builder from `MariaDB`. 

Contributions are welcome!
