### ISSUE TITLE
Cross namespace support?

### ISSUE THREAD

**Issue by cloudnull** [mariadb-operator/mariadb-operator#365]
Hello, 

This more of a help wanted than an actual bug, I think. When running the mariadb operator in the mariadb-system namespace and a galera cluster in a different namespace (in this case openstack), I see the operator reporting the following errors fairly consistently; however, I don't quite grok why this would be happening and how I'd solve this issue?

``` log
{"level":"error","ts":1707043603.518287,"msg":"Error reconciling SQL resource","controller":"grant","controllerGroup":"mariadb.mmontes.io","controllerKind":"Grant","Grant":{"name":"skyline-grant","namespace":"openstack"},"namespace":"openstack","name":"skyline-grant","reconcileID":"b552a16d-e07a-4bb4-8619-79c430c5893b","resource":"skyline-grant","error":"1 error occurred:\n\t* Error 1130: Host '10.233.91.124' is not allowed to connect to this MariaDB server\n\n","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).retryResult\n\t/app/pkg/controller/sql/controller.go:112\ngithub.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).Reconcile\n\t/app/pkg/controller/sql/controller.go:81\ngithub.com/mariadb-operator/mariadb-operator/controller.(*GrantReconciler).Reconcile\n\t/app/controller/grant_controller.go:63\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}

{"level":"error","ts":1707065220.7522292,"msg":"Error reconciling SQL resource","controller":"grant","controllerGroup":"mariadb.mmontes.io","controllerKind":"Grant","Grant":{"name":"cinder-grant","namespace":"openstack"},"namespace":"openstack","name":"cinder-grant","reconcileID":"4d7da9fc-e874-4249-a395-7f756158feb4","resource":"cinder-grant","error":"1 error occurred:\n\t* Error 1130: Host '10.233.91.124' is not allowed to connect to this MariaDB server\n\n","stacktrace":"github.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).retryResult\n\t/app/pkg/controller/sql/controller.go:112\ngithub.com/mariadb-operator/mariadb-operator/pkg/controller/sql.(*SqlReconciler).Reconcile\n\t/app/pkg/controller/sql/controller.go:81\ngithub.com/mariadb-operator/mariadb-operator/controller.(*GrantReconciler).Reconcile\n\t/app/controller/grant_controller.go:63\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227"}
```

All that being said, if I run the operator in the same namespace as the deployed galera cluster, everything seems to be working just fine. Maybe it's not supposed to work the way I'm attempting to set it up, maybe I'm doing it wrong? I've been searching around for docs on how this is supposed to work, and trying to make use of the examples, however, I'm at a bit of a loss; any help or insight on how this might work would be greatly appreciated.

**Environment details**:
- Kubernetes version: 1.28
- Kubernetes distribution: Vanilla
- mariadb-operator version: 0.0.24
- Install method: helm
- Install flavor: custom

**Additional context**
- operator manifest: https://github.com/cloudnull/genestack/blob/main/kustomize/mariadb-operator/kustomization.yaml
- galera cluster manifest: https://github.com/cloudnull/genestack/blob/main/kustomize/mariadb-cluster/base/mariadb-galera.yaml

**Comment by mmontes11** [comment]
Hey there @cloudnull ! Thanks for reporting this.

Regarding the error, it seems like the operator is trying to reconcile a `Grant` but for some reason MariaDB does not allow the operator IP (`10.233.91.124`) to perform such operator. It is strange because by default the operator has root privileges on MariaDB. Could you provide your `MariaDB` spec and the example you are following so I can try to reproduce it?

The cross-namespace support implies that the MariaDB references can point to resources in a different namespace. In this [example](https://github.com/mariadb-operator/mariadb-operator/tree/main/examples/manifests/cross-namespace), the [MariaDB](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/cross-namespace/mariadb.yaml) resource lives in the `mariadb` namespace while there is an application in the `app` namespace that connects to it by creating a cross-namespace [Connection](https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/cross-namespace/connection.yaml). This enables a multi-tenant model where multiple applications in different namespaces can share the same database.

In any case, cross-namespace references shouldn't have any implication at the MariaDB authorization level, unless I am missing something.

**Comment by mmontes11** [comment]
Just seen this error running locally the operator:
```bash
2024-02-12T18:49:16.880+0100    ERROR   Reconciler error        {"controller": "grant", "controllerGroup": "mariadb.mmontes.io", "controllerKind": "Grant", "Grant": {"name":"mariadb-galera-maxscale-sync","namespace":"default"}, "namespace": "default", "name": "mariadb-galera-maxscale-sync", "reconcileID": "8ffdbb6d-e17a-4039-98d4-679ba67282ee", "error": "error reconciling in TemplateReconciler: 1 error occurred:\n\t* Error 1130: Host '10.244.0.1' is not allowed to connect to this MariaDB server\n\n"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/martin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/martin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/martin/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227
``` 
Which results in the following log in MariaDB:
```bash
mariadb 2024-02-12 17:49:16 7188 [Warning] Aborted connection 7188 to db: 'unconnected' user: 'unauthentic
ated' host: '10.244.0.1' (This connection closed normally without authentication)
```

**Comment by mmontes11** [comment]
Hey there @cloudnull ! Sorry for the late response, we've been quite busy with [v0.0.26](https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.26) and [v0.0.27](https://github.com/mariadb-operator/mariadb-operator/releases/tag/v0.0.27),

It's been a while since I don't see the error in development, but it might be worth catching up. Feel free to join our [Slack channel](https://r.mariadb.com/join-community-slack) if you want to chat about it

**Comment by cloudnull** [comment]
Thanks for all your hard work on everything. I just joined the slack channel and will process an update to 0.0.27 and see where I get.

**Comment by mmontes11** [comment]
Great to hear this @cloudnull ! Let's keep an eye on the logs just in case, specially when `Connections` are deployed.
