### ISSUE TITLE
[Feature] Galera IPv6 support

### ISSUE THREAD

**Issue by djakobczak1** [mariadb-operator/mariadb-operator#458]
**Describe the solution you'd like**
Galera requires some additional configuration to use it in IPv6 environment. This configuration should be automated because it depends on pod IP. Changes could be applied to `0-galera.cnf` that is created during pod bootstrap.
Additionally, it might be necessary to provide additional `GaleraSpec` property to allow user adding custom `wsrep_provider_options`. Otherwise custom `wsrep_provider_options` user options provided in e.g. ConfigMap could override options added by operator for IPv6 environment.

**Describe alternatives you've considered**
Alternatively, it is possible to prepare init-container that can inject necessary configuration.

**Additional context**
If you do not mind, I would like to prepare PR that adds IPv6 support.

**Comment by mmontes11** [comment]
Hey there @djakobczak1 !  This makes total sense to me. 

The right place for supporting this would be the Galera init container, which is where we are populating the  `0-galera.cnf` config file. The Galera init container has already all the data you need for supporting this feature:
- `MariaDB` object obtained by calling the Kubernetes API. If you add extra fields, like maybe the `providerOptions`, they will be available for the init container too.
- `Pod` IP, available via the `POD_IP` environment variable, already obtained via the [Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/).

See the relevant parts of the code:
https://github.com/mariadb-operator/mariadb-operator/blob/cda2e95f6d4feab6143736ef3a56d9cf30509600/cmd/init/main.go#L105
https://github.com/mariadb-operator/mariadb-operator/blob/cda2e95f6d4feab6143736ef3a56d9cf30509600/pkg/galera/config/config.go#L87

We have some unit tests to make sure that the `0-galera.cnf` renders correctly. It would be great if you could add more cases here to make sure we cover the new config options:
https://github.com/mariadb-operator/mariadb-operator/blob/cda2e95f6d4feab6143736ef3a56d9cf30509600/pkg/galera/config/config_test.go#L12

In order to develop locally, you can refer to our development guide:
https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/DEVELOPMENT.md

You will need to build a new version of the init container by:
- Bumping the image [version](https://github.com/mariadb-operator/mariadb-operator/blob/cda2e95f6d4feab6143736ef3a56d9cf30509600/Makefile#L15)
- `make docker-build`
- `make docker-load`
- After doing so, you will be able to specify the new version [here](https://github.com/mariadb-operator/mariadb-operator/blob/cda2e95f6d4feab6143736ef3a56d9cf30509600/examples/manifests/mariadb_galera_full.yaml#L67)

Let me know if you need further help. Just leave a comment here or join our [Slack channel](https://r.mariadb.com/join-community-slack).

Thanks a lot! 🙏🏻

**Comment by mmontes11** [comment]
FYI, seems like KIND supports IPV6. Something we might be interested to use for automated tests:
https://kind.sigs.k8s.io/docs/user/configuration/#networking
