### ISSUE TITLE
[Feature] Configuring AntiAffinity for successful deployment of Metrics in 3 nodes cluster

### ISSUE THREAD

**Issue by behdadkh** [mariadb-operator/mariadb-operator#790]
**Is your feature request related to a problem? Please describe.**
Having a Kubernetes cluster with only 3 nodes which each takes one instance of a `replicas: 3` MariaDB cluster, 
will prevent the `metrics` instance to be scheduled when `enableAntiAffinity` is set to `true`

**Describe the solution you'd like**
To be able to successfully launch a MariaDB cluster with `3` replicas and its `metrics` deployment, in a Kubernetes cluster with only 3 nodes while having `enableAntiAffinity` set to `true`.

**Describe alternatives you've considered**
Right now, I had to set `enableAntiAffinity` to `false` to be able to launch the `metrics` deployment, which is not ideal if I decide to add a new node to the cluster.

**Environment details**:
- Kubernetes version: `1.25`
- Kubernetes distribution: Rancher
- mariadb-operator version: `0.27.0`
- Install method: Helm
- Install flavor: recommended

**Comment by mmontes11** [comment]
Hey there @behdadkh ! 

Since `v0.0.28` the metrics `Deployment` affinity rules are independent from the `MariaDB` ones, so you could potentially have the setup you describe above in a 3 node cluster and set `antiAffinityEnabled=true`. 

Refer to the migration guide to upgrade:
- https://github.com/mariadb-operator/mariadb-operator/blob/6171b061f944e10e29197fbdc7e4d1144b08352d/docs/UPGRADE_v0.0.28.md

**Comment by behdadkh** [comment]
Fantastic!

Thanks @mmontes11
